version : "3.8"


services:

  pipeline: 
    build: .
    command: python run_pipeline.py
    volumes:
      - ./:/app

  fastapi:
    build: .
    command: uvicorn main:app --reloads
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - pipeline
    
  streamlit:
    build: .
    command: streamlit run app.py
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      - pipeline

  mlflow:
    build: .
    command: mlflow ui 
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    depends_on:
      - pipeline
    
  airflow:
    build: .
    command: airflow standalone
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - pipeline
      